- name: including global variables
  include_vars: ../../../group_vars/globalvariables.yml

- name: updating the yum repostories
  yum: name=* state=latest
 
- name: installing puppet agent
  shell: rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
  ignore_errors: true
  
- name: Installing puppet agent
  yum: name=puppet  state=latest
 
- name: configuring puppet on agent 
  lineinfile: dest=/etc/puppet/puppet.conf line="server = {{ puppet_master_hostname }}"
 
- name: sending request to puppet master
  shell: puppet agent -t 